DutchTreat/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DutchTreat.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [MinLength(2, ErrorMessage = "Please enter a name.")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        public string UserEmail { get; set; }


        [MaxLength(75, ErrorMessage = "Your subject is to long please reduce it.")]
        public string Subject { get; set; }

        [Required]
        [MaxLength(250, ErrorMessage = "Your message is to long please reduce it.")]
        public string UserMessage { get; set; }

    }
}

DutchTreat/Controllers/AppController.cs
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Mvc;



namespace DutchTreat.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;

        public AppController(IMailService mailService)
        {
            _mailService = mailService;
        }



        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)


        {
            if (ModelState.IsValid)
            {
                //Send the email
                _mailService.SendMessage("shawn@wildermuth.com", model.Subject, $"From: {model.UserName} - {model.UserEmail}, Message: {model.UserMessage}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }



            ViewBag.Title = "Contact Us";

            return View();
        }


        [HttpGet("about")]
        public IActionResult About()
        {
            ViewBag.Title = "About Us";

            return View();
        }
    }
}

DutchTreat/Views/App/About.cshtml
<h2>About Us</h2>
<p>More to follow</p>

DutchTreat/Views/App/Contact.cshtml
@model ContactViewModel
@{

    ViewBag.Title = "Contact Us";
}
@section Scripts {
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="Instructions">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">* Indicates a required field</li>
                </ul>
            </div>
            <div class="form-group">
                <label asp-for="UserName">* Your Name:</label>
                <input type="text" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserEmail">* Email:</label>
                <input type="email" asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject">   Subject:</label>
                <input type="text" asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserMessage"> * Message:</label>
                <textarea rows="4" asp-for="UserMessage" class="form-control"></textarea>
                <span asp-validation-for="UserMessage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Send Message</button>
                <div class="text-success">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DutchTreat/Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<!--https://github.com/psauthor/BuildingASPNETCore2/tree/master/Resources-->
<div class="row">
    <div class="col-md-6">
        <div class="product-info">
            <img src="img/VanGogh.jpg" />
            <h3>Mug</h3>
            <ul class="product-props ">
                <li>Price $9.99</li>
                <li>Artist: Van Gogh</li>
                <li>Title: Grey Felt Hat </li>
                <li>Description: Self Portrit </li>
            </ul>
            <button id="buyButton" class="btn btn-success">Buy</button>
        </div>
        <div>
            <div id="loginToggle">Login</div>
            <form class="popup-form">
                <div>
                    <label>Username:</label>
                    <input />
                </div>
                @*<input type="text" name="UserName" size="15" maxlength="30" />*@
                <div>
                    <label>  Password:</label>
                    <input type="password" name="Password" size="15" maxlength="30" />
                </div>
                <div>
                    <input type="checkbox" />
                    <label>
                        Remember Me?
                    </label>
                </div>
                <div>
                    <input type="submit" value="Login" />
                </div>
                @*<input type="checkbox" name="Remember" value="yes" />
                    <button>Login</button>*@
            </form>
        </div>
    </div>

DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dutch Treat: @ViewBag.Title </title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <!--https://github.com/psauthor/BuildingASPNETCore2/tree/master/Resources-->
</head>
<body>
    <header class="container-fluid">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md ">
            <h1 class="navbar-brand"><i class="fa fa-paint-brush"></i> Welcome to Dutch Treat </h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse float-right">
                <ul class="navbar-nav float-right">
                    <li class="navbar-item">
                        <a class="nav-link" asp-controller="App" asp-action="Index">Home</a>
                    </li>
                    <li class="navbar-item">
                        <a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a>
                    </li>
                    <li class="navbar-item">
                        <a class="nav-link" asp-controller="App" asp-action="About">About</a>
                    </li>
                    @*  This is how the links look before we add in a asp-controller to link to our tag helper page which is a partial called  _ViewStart.cshtml
                        <li><a href="/">Home</a></li>
                        <li><a href="/app/contact">Contact</a> Contact</li>
                        <li><a href="/app/about">About</a>About</li>*@
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">Copyright 2017 Dutch Treat LLC </div>
    </footer>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.0.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    <script src="~/js/index.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>